### ISSUE TITLE
PlugY stashes are lost when converting S7 to S8

### ISSUE THREAD

**Issue by ghost** [BetweenWalls/PD2-Converter#5]
Hey,

It seems like all stash pages but the first one are lost when converting this save: [Vadmin.zip](https://github.com/BetweenWalls/PD2-Converter/files/12907994/Vadmin.zip). It's got plenty of items on the 2nd and 3rd stash pages if you open it in the S7, but only the 1st stash page is available in the converted save.

**Comment by BetweenWalls** [comment]
Oh dang. That was working earlier this season. I used it to convert all my s7 open wounds items and had 3 pages of them in a character's stash which transferred over fine. It seems one of the later updates broke it for d2x files. Anyway, it's working again in the most recent update. Tried it with your files and was able to see multiple stash pages of items.

**Comment by ghost** [comment]
Thanks a lot!
